# -*- coding: utf-8 -*-
"""https://github.com/datacode-tr/Assignment-008-9-Letters-Count-.git

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ekxfjs0rD6gLMp0NOjsBCyPiM7OSR9ht
"""

number=int(input('enter  number : '))
if number%4==0 and number%100==0 and number%400==0:
  print(number,'is leap year')
else:
    print(number,'is not leap year')

user= input('enter a sentence')
key =set(user)
value=[]
sayı_ls=[]
for i in key:
  sayı_ls.append([i, user.count(i)])
new_dict= dict(sayı_ls)
print(new_dict)



